language: node_js

node_js:
  - 8

addons:
  apt:
    packages:
      - python3
      - python3-pip

before_install:
  - pip3 install pip --upgrade --user
  - pip3 install ipykernel --user
  # Check that ipykernel will run
  - python -m ipykernel_launcher &

cache:
  directories:
    - node_modules

script:
  - make lint
  - make check
  - make cover
  - make docs

after_success:
  - bash <(curl -s https://codecov.io/bash)
