language: node_js

node_js:
  - 8

addons:
  apt:
    packages:
      - python3
      - python3-pip

before_install:
  - pip3 install --user travis ipykernel

cache:
  directories:
    - node_modules

script:
  - make lint
  - make check
  - make cover
  - make docs

after_success:
  - bash <(curl -s https://codecov.io/bash)
