language: node_js

node_js:
  - 8

addons:
  apt:
    sources:
      # Use deadsnakes for an up to date Python 2
      - sourceline: 'ppa:fkrull/deadsnakes-python2.7'
    packages:
      - python2.7
      - python-pip

before_install:
  - python --version
  - pip install pip --upgrade --user
  # Install ipykernel for testing of JupyterContext
  - pip install ipykernel --user

cache:
  directories:
    - node_modules

script:
  # Check that ipykernel will run
  - python -m ipykernel_launcher &

  - make lint
  - make check
  - make cover
  - make docs

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Deploy documentation to Github Pages
# See https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs
  on:
    branch: master
