window.esdocSearchIndex = [
  [
    "stencila-node/lib/contexts/context.js~context",
    "class/lib/contexts/Context.js~Context.html",
    "<span>Context</span> <span class=\"search-result-import-path\">stencila-node/lib/contexts/Context.js</span>",
    "class"
  ],
  [
    "stencila-node/lib/host/host.js~host",
    "class/lib/host/Host.js~Host.html",
    "<span>Host</span> <span class=\"search-result-import-path\">stencila-node/lib/host/Host.js</span>",
    "class"
  ],
  [
    "stencila-node/lib/host/hosthttpserver.js~hosthttpserver",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html",
    "<span>HostHttpServer</span> <span class=\"search-result-import-path\">stencila-node/lib/host/HostHttpServer.js</span>",
    "class"
  ],
  [
    "stencila-node/lib/contexts/javascriptcontext.js~javascriptcontext",
    "class/lib/contexts/JavascriptContext.js~JavascriptContext.html",
    "<span>JavascriptContext</span> <span class=\"search-result-import-path\">stencila-node/lib/contexts/JavascriptContext.js</span>",
    "class"
  ],
  [
    "stencila-node/lib/contexts/jupytercontext.js~jupytercontext",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html",
    "<span>JupyterContext</span> <span class=\"search-result-import-path\">stencila-node/lib/contexts/JupyterContext.js</span>",
    "class"
  ],
  [
    "stencila-node/lib/contexts/nodecontext.js~nodecontext",
    "class/lib/contexts/NodeContext.js~NodeContext.html",
    "<span>NodeContext</span> <span class=\"search-result-import-path\">stencila-node/lib/contexts/NodeContext.js</span>",
    "class"
  ],
  [
    "stencila-node/lib/contexts/sqlitecontext.js~sqlitecontext",
    "class/lib/contexts/SqliteContext.js~SqliteContext.html",
    "<span>SqliteContext</span> <span class=\"search-result-import-path\">stencila-node/lib/contexts/SqliteContext.js</span>",
    "class"
  ],
  [
    "lib/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "lib/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "lib/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "lib/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "lib/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "lib/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "lib/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "lib/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "lib/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "lib/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "lib/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "lib/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "lib/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "lib/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "lib/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "lib/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "lib/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "lib/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "lib/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "lib/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "lib/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "lib/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "lib/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "lib/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "lib/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "lib/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~String",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "lib/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "lib/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "lib/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "lib/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "lib/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "lib/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "lib/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "lib/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "lib/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "lib/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "lib/.external-ecmascript.js~null",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~string",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "lib/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "lib/contexts/context.js",
    "file/lib/contexts/Context.js.html",
    "lib/contexts/Context.js",
    "file"
  ],
  [
    "lib/contexts/context.js~context#_host",
    "class/lib/contexts/Context.js~Context.html#instance-member-_host",
    "lib/contexts/Context.js~Context#_host",
    "member"
  ],
  [
    "lib/contexts/context.js~context#_id",
    "class/lib/contexts/Context.js~Context.html#instance-member-_id",
    "lib/contexts/Context.js~Context#_id",
    "member"
  ],
  [
    "lib/contexts/context.js~context#_name",
    "class/lib/contexts/Context.js~Context.html#instance-member-_name",
    "lib/contexts/Context.js~Context#_name",
    "member"
  ],
  [
    "lib/contexts/context.js~context#_variables",
    "class/lib/contexts/Context.js~Context.html#instance-member-_variables",
    "lib/contexts/Context.js~Context#_variables",
    "member"
  ],
  [
    "lib/contexts/context.js~context#compile",
    "class/lib/contexts/Context.js~Context.html#instance-method-compile",
    "lib/contexts/Context.js~Context#compile",
    "method"
  ],
  [
    "lib/contexts/context.js~context#constructor",
    "class/lib/contexts/Context.js~Context.html#instance-constructor-constructor",
    "lib/contexts/Context.js~Context#constructor",
    "method"
  ],
  [
    "lib/contexts/context.js~context#evaluate",
    "class/lib/contexts/Context.js~Context.html#instance-method-evaluate",
    "lib/contexts/Context.js~Context#evaluate",
    "method"
  ],
  [
    "lib/contexts/context.js~context#execute",
    "class/lib/contexts/Context.js~Context.html#instance-method-execute",
    "lib/contexts/Context.js~Context#execute",
    "method"
  ],
  [
    "lib/contexts/context.js~context#host",
    "class/lib/contexts/Context.js~Context.html#instance-get-host",
    "lib/contexts/Context.js~Context#host",
    "member"
  ],
  [
    "lib/contexts/context.js~context#id",
    "class/lib/contexts/Context.js~Context.html#instance-get-id",
    "lib/contexts/Context.js~Context#id",
    "member"
  ],
  [
    "lib/contexts/context.js~context#libraries",
    "class/lib/contexts/Context.js~Context.html#instance-method-libraries",
    "lib/contexts/Context.js~Context#libraries",
    "method"
  ],
  [
    "lib/contexts/context.js~context#location",
    "class/lib/contexts/Context.js~Context.html#instance-get-location",
    "lib/contexts/Context.js~Context#location",
    "member"
  ],
  [
    "lib/contexts/context.js~context#name",
    "class/lib/contexts/Context.js~Context.html#instance-get-name",
    "lib/contexts/Context.js~Context#name",
    "member"
  ],
  [
    "lib/contexts/context.js~context#pack",
    "class/lib/contexts/Context.js~Context.html#instance-method-pack",
    "lib/contexts/Context.js~Context#pack",
    "method"
  ],
  [
    "lib/contexts/context.js~context#packpackage",
    "class/lib/contexts/Context.js~Context.html#instance-method-packPackage",
    "lib/contexts/Context.js~Context#packPackage",
    "method"
  ],
  [
    "lib/contexts/context.js~context#packpointer",
    "class/lib/contexts/Context.js~Context.html#instance-method-packPointer",
    "lib/contexts/Context.js~Context#packPointer",
    "method"
  ],
  [
    "lib/contexts/context.js~context#provide",
    "class/lib/contexts/Context.js~Context.html#instance-method-provide",
    "lib/contexts/Context.js~Context#provide",
    "method"
  ],
  [
    "lib/contexts/context.js~context#resolve",
    "class/lib/contexts/Context.js~Context.html#instance-method-resolve",
    "lib/contexts/Context.js~Context#resolve",
    "method"
  ],
  [
    "lib/contexts/context.js~context#unpack",
    "class/lib/contexts/Context.js~Context.html#instance-method-unpack",
    "lib/contexts/Context.js~Context#unpack",
    "method"
  ],
  [
    "lib/contexts/context.js~context#unpackpackage",
    "class/lib/contexts/Context.js~Context.html#instance-method-unpackPackage",
    "lib/contexts/Context.js~Context#unpackPackage",
    "method"
  ],
  [
    "lib/contexts/context.js~context#unpackpointer",
    "class/lib/contexts/Context.js~Context.html#instance-method-unpackPointer",
    "lib/contexts/Context.js~Context#unpackPointer",
    "method"
  ],
  [
    "lib/contexts/javascriptcontext.js",
    "file/lib/contexts/JavascriptContext.js.html",
    "lib/contexts/JavascriptContext.js",
    "file"
  ],
  [
    "lib/contexts/javascriptcontext.js~javascriptcontext#_compilefunction",
    "class/lib/contexts/JavascriptContext.js~JavascriptContext.html#instance-method-_compileFunction",
    "lib/contexts/JavascriptContext.js~JavascriptContext#_compileFunction",
    "method"
  ],
  [
    "lib/contexts/javascriptcontext.js~javascriptcontext#_libraries",
    "class/lib/contexts/JavascriptContext.js~JavascriptContext.html#instance-member-_libraries",
    "lib/contexts/JavascriptContext.js~JavascriptContext#_libraries",
    "member"
  ],
  [
    "lib/contexts/javascriptcontext.js~javascriptcontext#_variables",
    "class/lib/contexts/JavascriptContext.js~JavascriptContext.html#instance-member-_variables",
    "lib/contexts/JavascriptContext.js~JavascriptContext#_variables",
    "member"
  ],
  [
    "lib/contexts/javascriptcontext.js~javascriptcontext#compile",
    "class/lib/contexts/JavascriptContext.js~JavascriptContext.html#instance-method-compile",
    "lib/contexts/JavascriptContext.js~JavascriptContext#compile",
    "method"
  ],
  [
    "lib/contexts/javascriptcontext.js~javascriptcontext#constructor",
    "class/lib/contexts/JavascriptContext.js~JavascriptContext.html#instance-constructor-constructor",
    "lib/contexts/JavascriptContext.js~JavascriptContext#constructor",
    "method"
  ],
  [
    "lib/contexts/javascriptcontext.js~javascriptcontext#evaluatecall",
    "class/lib/contexts/JavascriptContext.js~JavascriptContext.html#instance-method-evaluateCall",
    "lib/contexts/JavascriptContext.js~JavascriptContext#evaluateCall",
    "method"
  ],
  [
    "lib/contexts/javascriptcontext.js~javascriptcontext#evaluateget",
    "class/lib/contexts/JavascriptContext.js~JavascriptContext.html#instance-method-evaluateGet",
    "lib/contexts/JavascriptContext.js~JavascriptContext#evaluateGet",
    "method"
  ],
  [
    "lib/contexts/javascriptcontext.js~javascriptcontext#execute",
    "class/lib/contexts/JavascriptContext.js~JavascriptContext.html#instance-method-execute",
    "lib/contexts/JavascriptContext.js~JavascriptContext#execute",
    "method"
  ],
  [
    "lib/contexts/javascriptcontext.js~javascriptcontext#libraries",
    "class/lib/contexts/JavascriptContext.js~JavascriptContext.html#instance-method-libraries",
    "lib/contexts/JavascriptContext.js~JavascriptContext#libraries",
    "method"
  ],
  [
    "lib/contexts/javascriptcontext.js~javascriptcontext#pack",
    "class/lib/contexts/JavascriptContext.js~JavascriptContext.html#instance-method-pack",
    "lib/contexts/JavascriptContext.js~JavascriptContext#pack",
    "method"
  ],
  [
    "lib/contexts/javascriptcontext.js~javascriptcontext#variables",
    "class/lib/contexts/JavascriptContext.js~JavascriptContext.html#instance-method-variables",
    "lib/contexts/JavascriptContext.js~JavascriptContext#variables",
    "method"
  ],
  [
    "lib/contexts/jupytercontext.js",
    "file/lib/contexts/JupyterContext.js.html",
    "lib/contexts/JupyterContext.js",
    "file"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#_config",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-member-_config",
    "lib/contexts/JupyterContext.js~JupyterContext#_config",
    "member"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#_connectionfile",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-member-_connectionFile",
    "lib/contexts/JupyterContext.js~JupyterContext#_connectionFile",
    "member"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#_iosocket",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-member-_ioSocket",
    "lib/contexts/JupyterContext.js~JupyterContext#_ioSocket",
    "member"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#_kernelinfo",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-member-_kernelInfo",
    "lib/contexts/JupyterContext.js~JupyterContext#_kernelInfo",
    "member"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#_process",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-member-_process",
    "lib/contexts/JupyterContext.js~JupyterContext#_process",
    "member"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#_request",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-method-_request",
    "lib/contexts/JupyterContext.js~JupyterContext#_request",
    "method"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#_requests",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-member-_requests",
    "lib/contexts/JupyterContext.js~JupyterContext#_requests",
    "member"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#_response",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-method-_response",
    "lib/contexts/JupyterContext.js~JupyterContext#_response",
    "method"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#_sessionid",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-member-_sessionId",
    "lib/contexts/JupyterContext.js~JupyterContext#_sessionId",
    "member"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#_shellsocket",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-member-_shellSocket",
    "lib/contexts/JupyterContext.js~JupyterContext#_shellSocket",
    "member"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#_spec",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-member-_spec",
    "lib/contexts/JupyterContext.js~JupyterContext#_spec",
    "member"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#_unbundle",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-method-_unbundle",
    "lib/contexts/JupyterContext.js~JupyterContext#_unbundle",
    "method"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#constructor",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-constructor-constructor",
    "lib/contexts/JupyterContext.js~JupyterContext#constructor",
    "method"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#debug",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-member-debug",
    "lib/contexts/JupyterContext.js~JupyterContext#debug",
    "member"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#execute",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-method-execute",
    "lib/contexts/JupyterContext.js~JupyterContext#execute",
    "method"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#finalize",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-method-finalize",
    "lib/contexts/JupyterContext.js~JupyterContext#finalize",
    "method"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#initialize",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-method-initialize",
    "lib/contexts/JupyterContext.js~JupyterContext#initialize",
    "method"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#kernel",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-member-kernel",
    "lib/contexts/JupyterContext.js~JupyterContext#kernel",
    "member"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext#timeout",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#instance-member-timeout",
    "lib/contexts/JupyterContext.js~JupyterContext#timeout",
    "member"
  ],
  [
    "lib/contexts/jupytercontext.js~jupytercontext.discover",
    "class/lib/contexts/JupyterContext.js~JupyterContext.html#static-method-discover",
    "lib/contexts/JupyterContext.js~JupyterContext.discover",
    "method"
  ],
  [
    "lib/contexts/nodecontext.js",
    "file/lib/contexts/NodeContext.js.html",
    "lib/contexts/NodeContext.js",
    "file"
  ],
  [
    "lib/contexts/nodecontext.js~nodecontext#compilefile",
    "class/lib/contexts/NodeContext.js~NodeContext.html#instance-method-compileFile",
    "lib/contexts/NodeContext.js~NodeContext#compileFile",
    "method"
  ],
  [
    "lib/contexts/nodecontext.js~nodecontext#compilelibrary",
    "class/lib/contexts/NodeContext.js~NodeContext.html#instance-method-compileLibrary",
    "lib/contexts/NodeContext.js~NodeContext#compileLibrary",
    "method"
  ],
  [
    "lib/contexts/nodecontext.js~nodecontext#executelibrary",
    "class/lib/contexts/NodeContext.js~NodeContext.html#instance-method-executeLibrary",
    "lib/contexts/NodeContext.js~NodeContext#executeLibrary",
    "method"
  ],
  [
    "lib/contexts/sqlitecontext.js",
    "file/lib/contexts/SqliteContext.js.html",
    "lib/contexts/SqliteContext.js",
    "file"
  ],
  [
    "lib/contexts/sqlitecontext.js~sqlitecontext#_appenderror",
    "class/lib/contexts/SqliteContext.js~SqliteContext.html#instance-method-_appendError",
    "lib/contexts/SqliteContext.js~SqliteContext#_appendError",
    "method"
  ],
  [
    "lib/contexts/sqlitecontext.js~sqlitecontext#_db",
    "class/lib/contexts/SqliteContext.js~SqliteContext.html#instance-member-_db",
    "lib/contexts/SqliteContext.js~SqliteContext#_db",
    "member"
  ],
  [
    "lib/contexts/sqlitecontext.js~sqlitecontext#_interpolatesql",
    "class/lib/contexts/SqliteContext.js~SqliteContext.html#instance-method-_interpolateSql",
    "lib/contexts/SqliteContext.js~SqliteContext#_interpolateSql",
    "method"
  ],
  [
    "lib/contexts/sqlitecontext.js~sqlitecontext#_pack",
    "class/lib/contexts/SqliteContext.js~SqliteContext.html#instance-method-_pack",
    "lib/contexts/SqliteContext.js~SqliteContext#_pack",
    "method"
  ],
  [
    "lib/contexts/sqlitecontext.js~sqlitecontext#_tableinputs",
    "class/lib/contexts/SqliteContext.js~SqliteContext.html#instance-method-_tableInputs",
    "lib/contexts/SqliteContext.js~SqliteContext#_tableInputs",
    "method"
  ],
  [
    "lib/contexts/sqlitecontext.js~sqlitecontext#_transpilesql",
    "class/lib/contexts/SqliteContext.js~SqliteContext.html#instance-method-_transpileSql",
    "lib/contexts/SqliteContext.js~SqliteContext#_transpileSql",
    "method"
  ],
  [
    "lib/contexts/sqlitecontext.js~sqlitecontext#_unpack",
    "class/lib/contexts/SqliteContext.js~SqliteContext.html#instance-method-_unpack",
    "lib/contexts/SqliteContext.js~SqliteContext#_unpack",
    "method"
  ],
  [
    "lib/contexts/sqlitecontext.js~sqlitecontext#compile",
    "class/lib/contexts/SqliteContext.js~SqliteContext.html#instance-method-compile",
    "lib/contexts/SqliteContext.js~SqliteContext#compile",
    "method"
  ],
  [
    "lib/contexts/sqlitecontext.js~sqlitecontext#constructor",
    "class/lib/contexts/SqliteContext.js~SqliteContext.html#instance-constructor-constructor",
    "lib/contexts/SqliteContext.js~SqliteContext#constructor",
    "method"
  ],
  [
    "lib/contexts/sqlitecontext.js~sqlitecontext#execute",
    "class/lib/contexts/SqliteContext.js~SqliteContext.html#instance-method-execute",
    "lib/contexts/SqliteContext.js~SqliteContext#execute",
    "method"
  ],
  [
    "lib/contexts/sqlitecontext.js~sqlitecontext#outputs",
    "class/lib/contexts/SqliteContext.js~SqliteContext.html#instance-method-outputs",
    "lib/contexts/SqliteContext.js~SqliteContext#outputs",
    "method"
  ],
  [
    "lib/contexts/sqlitecontext.js~sqlitecontext#provide",
    "class/lib/contexts/SqliteContext.js~SqliteContext.html#instance-method-provide",
    "lib/contexts/SqliteContext.js~SqliteContext#provide",
    "method"
  ],
  [
    "lib/contexts/sqlitecontext.js~sqlitecontext#resolve",
    "class/lib/contexts/SqliteContext.js~SqliteContext.html#instance-method-resolve",
    "lib/contexts/SqliteContext.js~SqliteContext#resolve",
    "method"
  ],
  [
    "lib/host/host.js",
    "file/lib/host/Host.js.html",
    "lib/host/Host.js",
    "file"
  ],
  [
    "lib/host/host.js~host#_counts",
    "class/lib/host/Host.js~Host.html#instance-member-_counts",
    "lib/host/Host.js~Host#_counts",
    "member"
  ],
  [
    "lib/host/host.js~host#_heartbeat",
    "class/lib/host/Host.js~Host.html#instance-member-_heartbeat",
    "lib/host/Host.js~Host#_heartbeat",
    "member"
  ],
  [
    "lib/host/host.js~host#_id",
    "class/lib/host/Host.js~Host.html#instance-member-_id",
    "lib/host/Host.js~Host#_id",
    "member"
  ],
  [
    "lib/host/host.js~host#_instances",
    "class/lib/host/Host.js~Host.html#instance-member-_instances",
    "lib/host/Host.js~Host#_instances",
    "member"
  ],
  [
    "lib/host/host.js~host#_key",
    "class/lib/host/Host.js~Host.html#instance-member-_key",
    "lib/host/Host.js~Host#_key",
    "member"
  ],
  [
    "lib/host/host.js~host#_machine",
    "class/lib/host/Host.js~Host.html#instance-member-_machine",
    "lib/host/Host.js~Host#_machine",
    "member"
  ],
  [
    "lib/host/host.js~host#_peers",
    "class/lib/host/Host.js~Host.html#instance-member-_peers",
    "lib/host/Host.js~Host#_peers",
    "member"
  ],
  [
    "lib/host/host.js~host#_servers",
    "class/lib/host/Host.js~Host.html#instance-member-_servers",
    "lib/host/Host.js~Host#_servers",
    "member"
  ],
  [
    "lib/host/host.js~host#_started",
    "class/lib/host/Host.js~Host.html#instance-member-_started",
    "lib/host/Host.js~Host#_started",
    "member"
  ],
  [
    "lib/host/host.js~host#authorizetoken",
    "class/lib/host/Host.js~Host.html#instance-method-authorizeToken",
    "lib/host/Host.js~Host#authorizeToken",
    "method"
  ],
  [
    "lib/host/host.js~host#call",
    "class/lib/host/Host.js~Host.html#instance-method-call",
    "lib/host/Host.js~Host#call",
    "method"
  ],
  [
    "lib/host/host.js~host#compile",
    "class/lib/host/Host.js~Host.html#instance-method-compile",
    "lib/host/Host.js~Host#compile",
    "method"
  ],
  [
    "lib/host/host.js~host#constructor",
    "class/lib/host/Host.js~Host.html#instance-constructor-constructor",
    "lib/host/Host.js~Host#constructor",
    "method"
  ],
  [
    "lib/host/host.js~host#create",
    "class/lib/host/Host.js~Host.html#instance-method-create",
    "lib/host/Host.js~Host#create",
    "method"
  ],
  [
    "lib/host/host.js~host#destroy",
    "class/lib/host/Host.js~Host.html#instance-method-destroy",
    "lib/host/Host.js~Host#destroy",
    "method"
  ],
  [
    "lib/host/host.js~host#discoverpeers",
    "class/lib/host/Host.js~Host.html#instance-method-discoverPeers",
    "lib/host/Host.js~Host#discoverPeers",
    "method"
  ],
  [
    "lib/host/host.js~host#environs",
    "class/lib/host/Host.js~Host.html#instance-method-environs",
    "lib/host/Host.js~Host#environs",
    "method"
  ],
  [
    "lib/host/host.js~host#generatetoken",
    "class/lib/host/Host.js~Host.html#instance-method-generateToken",
    "lib/host/Host.js~Host#generateToken",
    "method"
  ],
  [
    "lib/host/host.js~host#get",
    "class/lib/host/Host.js~Host.html#instance-method-get",
    "lib/host/Host.js~Host#get",
    "method"
  ],
  [
    "lib/host/host.js~host#heartbeat",
    "class/lib/host/Host.js~Host.html#instance-method-heartbeat",
    "lib/host/Host.js~Host#heartbeat",
    "method"
  ],
  [
    "lib/host/host.js~host#id",
    "class/lib/host/Host.js~Host.html#instance-get-id",
    "lib/host/Host.js~Host#id",
    "member"
  ],
  [
    "lib/host/host.js~host#key",
    "class/lib/host/Host.js~Host.html#instance-get-key",
    "lib/host/Host.js~Host#key",
    "member"
  ],
  [
    "lib/host/host.js~host#machine",
    "class/lib/host/Host.js~Host.html#instance-get-machine",
    "lib/host/Host.js~Host#machine",
    "member"
  ],
  [
    "lib/host/host.js~host#manifest",
    "class/lib/host/Host.js~Host.html#instance-method-manifest",
    "lib/host/Host.js~Host#manifest",
    "method"
  ],
  [
    "lib/host/host.js~host#process",
    "class/lib/host/Host.js~Host.html#instance-get-process",
    "lib/host/Host.js~Host#process",
    "member"
  ],
  [
    "lib/host/host.js~host#register",
    "class/lib/host/Host.js~Host.html#instance-method-register",
    "lib/host/Host.js~Host#register",
    "method"
  ],
  [
    "lib/host/host.js~host#registerpeer",
    "class/lib/host/Host.js~Host.html#instance-method-registerPeer",
    "lib/host/Host.js~Host#registerPeer",
    "method"
  ],
  [
    "lib/host/host.js~host#requestpeer",
    "class/lib/host/Host.js~Host.html#instance-method-requestPeer",
    "lib/host/Host.js~Host#requestPeer",
    "method"
  ],
  [
    "lib/host/host.js~host#resolve",
    "class/lib/host/Host.js~Host.html#instance-method-resolve",
    "lib/host/Host.js~Host#resolve",
    "method"
  ],
  [
    "lib/host/host.js~host#run",
    "class/lib/host/Host.js~Host.html#instance-method-run",
    "lib/host/Host.js~Host#run",
    "method"
  ],
  [
    "lib/host/host.js~host#servers",
    "class/lib/host/Host.js~Host.html#instance-get-servers",
    "lib/host/Host.js~Host#servers",
    "member"
  ],
  [
    "lib/host/host.js~host#shutdown",
    "class/lib/host/Host.js~Host.html#instance-method-shutdown",
    "lib/host/Host.js~Host#shutdown",
    "method"
  ],
  [
    "lib/host/host.js~host#spawn",
    "class/lib/host/Host.js~Host.html#instance-method-spawn",
    "lib/host/Host.js~Host#spawn",
    "method"
  ],
  [
    "lib/host/host.js~host#spawnpeer",
    "class/lib/host/Host.js~Host.html#instance-method-spawnPeer",
    "lib/host/Host.js~Host#spawnPeer",
    "method"
  ],
  [
    "lib/host/host.js~host#start",
    "class/lib/host/Host.js~Host.html#instance-method-start",
    "lib/host/Host.js~Host#start",
    "method"
  ],
  [
    "lib/host/host.js~host#startup",
    "class/lib/host/Host.js~Host.html#instance-method-startup",
    "lib/host/Host.js~Host#startup",
    "method"
  ],
  [
    "lib/host/host.js~host#stop",
    "class/lib/host/Host.js~Host.html#instance-method-stop",
    "lib/host/Host.js~Host#stop",
    "method"
  ],
  [
    "lib/host/host.js~host#types",
    "class/lib/host/Host.js~Host.html#instance-get-types",
    "lib/host/Host.js~Host#types",
    "member"
  ],
  [
    "lib/host/host.js~host#urls",
    "class/lib/host/Host.js~Host.html#instance-get-urls",
    "lib/host/Host.js~Host#urls",
    "member"
  ],
  [
    "lib/host/host.js~host#view",
    "class/lib/host/Host.js~Host.html#instance-method-view",
    "lib/host/Host.js~Host#view",
    "method"
  ],
  [
    "lib/host/host.js~host.issuperuser",
    "class/lib/host/Host.js~Host.html#static-method-isSuperUser",
    "lib/host/Host.js~Host.isSuperUser",
    "method"
  ],
  [
    "lib/host/host.js~host.tempdir",
    "class/lib/host/Host.js~Host.html#static-method-tempDir",
    "lib/host/Host.js~Host.tempDir",
    "method"
  ],
  [
    "lib/host/host.js~host.userdir",
    "class/lib/host/Host.js~Host.html#static-method-userDir",
    "lib/host/Host.js~Host.userDir",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js",
    "file/lib/host/HostHttpServer.js.html",
    "lib/host/HostHttpServer.js",
    "file"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#_address",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-member-_address",
    "lib/host/HostHttpServer.js~HostHttpServer#_address",
    "member"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#_host",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-member-_host",
    "lib/host/HostHttpServer.js~HostHttpServer#_host",
    "member"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#_port",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-member-_port",
    "lib/host/HostHttpServer.js~HostHttpServer#_port",
    "member"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#_server",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-member-_server",
    "lib/host/HostHttpServer.js~HostHttpServer#_server",
    "member"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#address",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-get-address",
    "lib/host/HostHttpServer.js~HostHttpServer#address",
    "member"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#call",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-method-call",
    "lib/host/HostHttpServer.js~HostHttpServer#call",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#constructor",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-constructor-constructor",
    "lib/host/HostHttpServer.js~HostHttpServer#constructor",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#create",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-method-create",
    "lib/host/HostHttpServer.js~HostHttpServer#create",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#destroy",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-method-destroy",
    "lib/host/HostHttpServer.js~HostHttpServer#destroy",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#error",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-method-error",
    "lib/host/HostHttpServer.js~HostHttpServer#error",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#error400",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-method-error400",
    "lib/host/HostHttpServer.js~HostHttpServer#error400",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#error403",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-method-error403",
    "lib/host/HostHttpServer.js~HostHttpServer#error403",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#error404",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-method-error404",
    "lib/host/HostHttpServer.js~HostHttpServer#error404",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#error500",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-method-error500",
    "lib/host/HostHttpServer.js~HostHttpServer#error500",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#get",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-method-get",
    "lib/host/HostHttpServer.js~HostHttpServer#get",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#handle",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-method-handle",
    "lib/host/HostHttpServer.js~HostHttpServer#handle",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#home",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-method-home",
    "lib/host/HostHttpServer.js~HostHttpServer#home",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#manifest",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-method-manifest",
    "lib/host/HostHttpServer.js~HostHttpServer#manifest",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#port",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-get-port",
    "lib/host/HostHttpServer.js~HostHttpServer#port",
    "member"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#route",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-method-route",
    "lib/host/HostHttpServer.js~HostHttpServer#route",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#shutdown",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-method-shutdown",
    "lib/host/HostHttpServer.js~HostHttpServer#shutdown",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#start",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-method-start",
    "lib/host/HostHttpServer.js~HostHttpServer#start",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#startup",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-method-startup",
    "lib/host/HostHttpServer.js~HostHttpServer#startup",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#statico",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-method-statico",
    "lib/host/HostHttpServer.js~HostHttpServer#statico",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#stop",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-method-stop",
    "lib/host/HostHttpServer.js~HostHttpServer#stop",
    "method"
  ],
  [
    "lib/host/hosthttpserver.js~hosthttpserver#url",
    "class/lib/host/HostHttpServer.js~HostHttpServer.html#instance-get-url",
    "lib/host/HostHttpServer.js~HostHttpServer#url",
    "member"
  ],
  [
    "lib/index.js",
    "file/lib/index.js.html",
    "lib/index.js",
    "file"
  ]
]